# SQL export generated by CocoaMySQL
# Version 0.7b6
# http://cocoamysql.sourceforge.net
#
# Host: 127.0.0.1 (MySQL 5.0.67)
# Database: knopdemo
# Generation Time: 2008-09-11 13:13:06 +0200
# Encoding: UTF-8 Unicode (utf8)
# ************************************************************

# Dump of table customer
# ------------------------------------------------------------

CREATE TABLE `customer` (
  `id` bigint(20) unsigned NOT NULL auto_increment,
  `firstname` varchar(255) NOT NULL default '',
  `lastname` varchar(255) NOT NULL default '',
  `email` varchar(255) NOT NULL default '',
  `password` varchar(255) character set latin1 collate latin1_bin NOT NULL default '',
  `enabled` tinyint(4) NOT NULL default '0',
  `message` text NOT NULL,
  `moddate` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `keyfield` varchar(255) NOT NULL,
  `lockfield` varchar(255) NOT NULL,
  PRIMARY KEY  (`id`),
  KEY `keyfield` (`keyfield`),
  KEY `lockfield` (`lockfield`)
) ENGINE=MyISAM AUTO_INCREMENT=124 DEFAULT CHARSET=latin1;

INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('1','Demo','User','demo@demo.com','demo','1','','2008-09-11 10:06:48','lo9rnb7ilr6r6','1|2008-09-11 10:06:48');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('2','pljks','pluj','pljks@pluj.com','sdasd','1','','2008-09-09 16:36:39','hgh7y15531ki','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('3','Nisse','Hult','','','0','','2008-09-07 21:57:52','lti1sf1b13g51','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('4','Kalle','Svenssons','kalle@svensson.se','','0','','2008-06-03 13:41:27','itxnqg6ohrtl1','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('5','Kalle','Nilsson','','','0','','2008-09-09 14:48:29','ip873gswcjpgq','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('6','Margaret','Hsuan','','','0','','2008-09-09 16:36:54','h71gpdu8khhok','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('7','Merat','Liyuan','','','0','','2007-12-03 15:17:32','ib34zdu8khhok','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('8','Horst','Bruno','','','0','','2007-06-13 15:26:23','ii3j6du8khhok','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('9','Murat','Louis','','','0','','2007-04-19 09:24:36','iozl0du8khhok','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('10','Andrew','Louis','','','1','','2008-09-11 10:05:33','jcn4bdu8khhok','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('11','Barry','Jacques','','','0','','2008-09-09 14:48:29','jk5dsdu8khhok','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('12','Harry','Susumu','','','0','','2007-09-06 16:32:25','jpq4ldu8khhok','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('13','Marty','Sedovic','','','0','','2007-04-19 09:24:54','jw34gdu8khhok','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('14','Audrey','David','','','0','','2008-09-11 09:37:01','j3qyqdu8khhok','1|2008-09-11 09:37:01');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('15','Kimberly','Tovah','','','0','','2007-03-01 13:34:07','j64r7du8khhok','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('16','Beverly','Vivek','','','0','','2007-03-01 07:47:09','ka46wdu8khhok','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('17','Thierry','Himawan','','','0','','2007-01-12 20:42:53','kem5idu8khhok','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('18','Jerry','Pravin','','','0','','2007-01-12 13:30:28','kj9y5du8khhok','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('19','Jerry','Edwin','','','0','','2007-01-12 13:30:28','kohrjdu8khhok','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('20','Kerry','Kevan','','','0','','2007-01-12 13:30:28','kssq2du8khhok','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('21','Perry','Stevan','','','0','','2007-01-12 13:30:28','kwl47du8khhok','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('22','Terry','Steven','','','0','','2007-01-12 13:30:28','k2ukjdu8khhok','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('23','Geoffrey','Kevin','','','0','','2007-01-12 13:30:28','k6g74du8khhok','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('24','Jeffrey','Devon','','','0','','2007-03-04 17:26:03','ls53fdu8khhok','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('25','Jeffrey','Kevyn','','','0','','2007-01-12 13:30:28','lyz9wdu8khhok','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('26','Corey','Sylvan','','','0','','2007-01-12 13:30:28','l3ds8du8khhok','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('27','Murray','Calvin','','','0','','2007-01-12 13:30:29','f9pt2dztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('28','Clarissa','Alvin','','','0','','2007-02-09 00:23:19','gc9fddztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('29','Marshal','Kelvin','','','0','','2007-01-23 14:08:12','ggnfxdztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('30','Revised','Donovan','','','0','','2007-09-07 08:40:12','gk2t7dztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('31','Jesse','Marvin','','','0','','2007-01-12 13:30:29','gpnz0dztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('32','Celeste','Erwin','','','0','','2007-01-12 13:30:29','gumbydztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('33','Jelske','Irvin','','','0','','2007-03-04 17:51:46','gzintdztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('34','Huashi','Irwin','','','0','','2007-01-12 13:30:29','g6dfkdztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('35','Cristi','Kayvan','','','0','','2007-01-12 13:30:29','g9q7ldztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('36','Kristi','Trevor','','','0','','2007-01-12 13:30:29','hdwq1dztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('37','Kristi','Oliver','','','0','','2007-02-09 00:24:38','hhoi5dztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('38','Hirotoshi','Pitawas','','','0','','2007-02-09 00:24:38','hmelmdztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('39','Hitoshi','Travis','','','0','','2007-01-12 13:30:29','hp6gsdztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('40','Rajarshi','Lewis','','','0','','2007-01-12 13:30:29','huzxqdztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('41','Jussi','Jurevis','','','0','','2007-01-12 13:30:29','h1ekzdztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('42','Kusum','Srinivas','','','0','','2007-01-12 20:30:18','h5zv1dztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('43','Srinivasan','Elvis','','','0','','2007-01-12 13:30:29','h9pf8dztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('44','Jason','Jarvis','','','0','','2007-01-12 13:30:29','id46edztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('45','Mason','Dewey','','','0','','2007-01-12 13:30:29','ihvnydztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('46','Jacobson','Harvey','','','0','','2007-01-12 13:30:29','inqrpdztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('47','Knudsen','Roxie','','','0','','2007-01-12 13:30:29','irsfsdztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('48','Sundaresan','Alexis','','','0','','2007-01-12 13:30:29','iu6kldztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('49','Tollefsen','Blayne','','','0','','2007-01-19 08:39:50','iyzyadztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('50','Tahsin','Dwayne','','','0','','2007-01-12 13:30:29','i3dladztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('51','Alison','Wayne','second','','0','','2007-09-27 09:54:02','i83p1dztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('52','Wilson','Clyde','','','0','','2007-03-04 17:08:00','jdommdztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('53','Olson','Boyce','','','0','','2007-01-12 13:30:29','jhlb4dztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('54','Benson','Joyce','','','0','','2007-11-05 13:57:39','jmxeldztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('55','Anderson','Doyle','','','0','','2008-09-11 00:23:45','jtur6dztx762c','1|2008-09-11 00:23:45');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('56','Sassan','Bryce','','','0','','2007-01-12 13:30:29','jxcr0dztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('57','Srivatsan','Suyog','','','0','','2007-01-12 13:30:29','j1tmedztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('58','Susan','Shyam','','','0','','2007-01-12 13:30:29','j550xdztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('59','Dawson','Rayan','','','0','','2007-01-12 13:30:29','j93uddztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('60','Francisco','Glynn','','','0','','2008-09-08 23:17:17','ke1n4dztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('61','Josip','Jianyun','','','0','','2007-01-12 13:30:29','kiifedztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('62','Mosur','Bryan','','','0','','2007-08-30 00:06:14','kmnu2dztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('63','Jesus','Nguyen','','','0','','2007-01-12 13:30:29','kqabvdztx762c','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('64','Naoto','Coleen','','','0','','2008-01-22 22:16:32','gyuq3emsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('65','Malcolm','Charleen','','','0','','2007-01-12 13:32:34','hdi0pemsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('66','Nicolo','Glenn','','','0','','2007-01-12 13:32:34','hgn47emsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('67','Francois','Toerless','','','0','','2007-01-12 13:32:34','hkh4eemsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('68','Scott','Pamela','','','0','','2007-01-12 13:32:34','hou9eemsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('69','Pandora','Ramesh','','','0','','2007-01-12 13:32:34','htcwremsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('70','Isidore','Emmett','','','0','','2007-01-12 13:32:34','h3n4aemsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('71','Theodore','Kenneth','','','0','','2007-01-12 13:32:34','ighg2emsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('72','Rudolf','Ramneek','','','0','','2007-01-12 13:32:34','ivm8bemsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('73','Ramadoss','Ernest','','','0','','2007-01-12 13:32:34','iy8ljemsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('74','Leora','Noemi','','','0','','2007-01-12 13:32:34','i2x2eemsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('75','Geoff','Rupert','','','0','','2007-01-12 13:32:34','i6655emsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('76','Bradford','Teresa','','','0','','2007-01-12 16:47:40','jj2euemsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('77','Clifford','Gregg','','','0','','2007-02-26 11:38:37','jvbwoemsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('78','Sanford','Naresh','','','0','','2007-01-12 13:32:34','j9pt4emsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('79','Gregory','Suresh','','','0','','2007-01-12 13:32:34','kfposemsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('80','Those','Darrell','','','0','','2007-01-12 13:32:34','kkb3oemsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('81','Soohong','Maureen','','','0','','2007-01-12 13:32:34','kxfkpemsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('82','Anthony','Dripper','a thing','','0','','2008-09-11 09:47:05','k2d4xemsuxpza','1|2008-09-11 09:47:05');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('83','Piotr','Brent','','','0','','2008-09-08 23:15:51','k6xt2emsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('84','Elliott','Trent','','','0','','2007-01-12 13:32:34','lxaroemsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('85','Floyd','Laurent','','','0','','2007-08-31 00:07:40','l0vumemsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('86','Lloyd','Brett','','','0','','2007-01-12 13:32:35','l4xvremsuxpza','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('87','Edmond','Everett','','','0','','2007-01-12 13:32:35','gcusgerd8ofc2','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('88','Raymond','Barrett','','','0','','2007-03-04 15:14:29','gl1jperd8ofc2','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('89','Mahmoud','Jeremy','','','0','','2007-01-12 13:32:35','g0k0verd8ofc2','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('90','Damone','Joseph','','','0','','2007-01-12 13:32:35','g93hperd8ofc2','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('91','Seymour','Russell','','','0','','2007-01-12 13:32:35','hjzboerd8ofc2','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('92','Lenora','Steve','','','0','','2007-01-12 13:32:35','hy6u8erd8ofc2','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('93','Arnold','Sorani','1,3','','0','','2007-09-27 10:00:59','h2gxjerd8ofc2','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('94','Masanobu','Lowell','','','0','','2007-01-12 13:32:35','h6b5ferd8ofc2','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('95','Brooke','Avery','','','0','','2008-09-10 22:52:31','h9yd1erd8ofc2','1|2008-09-10 22:52:31');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('96','Moore','Jayesh','','','0','','2007-01-12 13:32:35','id3j5erd8ofc2','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('97','Woody','Rafik','','','0','','2007-01-12 13:32:35','ikozkerd8ofc2','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('98','Spock','Stefan','','','0','','2007-01-12 13:32:35','iy3m9erd8ofc2','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('99','Harold','Jeffie','','','0','','2007-01-12 13:32:35','jkdqaerd8ofc2','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('100','Carole','Lucifer','','','0','','2007-02-24 11:38:39','jpcz4erd8ofc2','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('101','Jerome','Jennifer','','','0','','2007-01-12 13:32:35','jtsneerd8ofc2','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('102','Phiroze','Sofia','','','0','','2007-01-12 13:32:35','jxfkcerd8ofc2','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('103','Farouk','Christofer','','','0','','2007-01-12 13:32:35','kbl63erd8ofc2','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('104','Mysore','Irfan','','','0','','2007-01-12 13:32:35','klhloerd8ofc2','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('105','Anatole','Toufic','third','','0','','2008-09-11 00:16:12','k2lmterd8ofc2','1|2008-09-11 00:16:12');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('106','Shutoku','Raghu','','','0','','2007-01-12 13:32:35','lgiuyerd8ofc2','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('107','Anatoly','Edgar','second','','0','','2008-09-11 09:57:37','l5lqperd8ofc2','1|2008-09-11 09:57:37');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('108','Antony','Rodger','third','','0','','2008-09-11 09:48:12','gbkojevzme4qu','1|2008-09-11 09:48:12');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('109','Elwood','Gregge','','','0','','2007-01-12 13:32:36','geyr9evzme4qu','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('110','Stephe','Gregor','','','0','','2007-01-12 13:32:36','gi3mwevzme4qu','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('111','Philippe','Peggy','','','0','','2007-01-12 13:32:36','gmgxaevzme4qu','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('112','Christophe','Stagger','','','0','','2007-02-24 11:50:50','gq7y5evzme4qu','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('113','Jean-Christophe','Tigger','','','0','','2007-01-12 13:32:36','gw0brevzme4qu','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('114','Joan','Shiller','','','0','','2007-02-27 22:14:38','ga5wddcu17b6f','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('115','zzz','adfa','','','0','','2007-01-19 00:02:02','lgo0igoayug27','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('116','adsad','sasa','','','0','','2008-09-11 00:24:17','jy261xkshmqy','1|2008-09-11 00:24:17');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('117','James','Grant','','','0','','2007-02-27 22:12:39','lvfiycpv5hs9i','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('118','wewewe','','','','0','','2007-03-01 11:57:03','gef2jhtnfluqu','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('119','Nisse','Hult','','','0','','2007-03-04 19:26:47','krn7edhggei0g','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('120','test','test','','','0','','2008-03-04 23:08:04','ldj6zho3pe5v5','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('121','Nisse','Hult','','','0','Hello world!','2008-07-02 00:12:24','','');
INSERT INTO `customer` (`id`,`firstname`,`lastname`,`email`,`password`,`enabled`,`message`,`moddate`,`keyfield`,`lockfield`) VALUES ('122','yafa','yodo','','','0','Hello Again','2008-07-02 00:16:21','','');


